export enum EEnvType {
  PORT = 'PORT',
  TRANSPORT_PORT = 'TRANSPORT_PORT',
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  JWT_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME',
  FALLBACK_LANGUAGE = 'FALLBACK_LANGUAGE',
  NATS_ENABLED = 'NATS_ENABLED',

  AWS_S3_ACCESS_KEY_ID = 'AWS_S3_ACCESS_KEY_ID',
  AWS_S3_SECRET_ACCESS_KEY = 'AWS_S3_SECRET_ACCESS_KEY',
  AWS_S3_BUCKET_REGION = 'AWS_S3_BUCKET_REGION',
  AWS_S3_API_VERSION = 'AWS_S3_API_VERSION',
  AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET_NAME',
  AWS_S3_LINK = 'AWS_S3_LINK',

  NATS_HOST = 'NATS_HOST',
  NATS_PORT = 'NATS_PORT',
}
